version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-socialmedia}
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-socialmedia}
      MODEL_API_URL: http://models:8001
    ports:
      - "8000:8000"
    depends_on:
      - db
      - models

  models:
    build:
      context: .
      dockerfile: Dockerfile.models
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-socialmedia}
    ports:
      - "8001:8001"
    depends_on:
      - db

  simulator:
    build:
      context: .
      dockerfile: Dockerfile.simulator
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-socialmedia}
      API_URL: http://api:8000
    depends_on:
      - api
      - db

volumes:
  postgres_data: